[project]
name = 'Blockchain-Based-Retail-Staff-Training-Compliance'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.completion-tracking]
path = 'contracts/completion-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.store-verification]
path = 'contracts/store-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.training-requirement]
path = 'contracts/training-requirement.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
